api/core/urls.py
from core.views import (
    AttendantViewSet,
    CustomerGroupViewSet,
    CustomerUpdateViewSet,
    CustomerViewSet,
    UserViewSet,
)
from rest_framework import routers

r = routers.DefaultRouter()
r.register("users", UserViewSet)
r.register("attendants", AttendantViewSet)
r.register("customers", CustomerViewSet)
r.register("updates", CustomerUpdateViewSet)
r.register("groups", CustomerGroupViewSet)

urlpatterns = r.urls

api/support/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework import permissions
from support import settings

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("auth/", include("dj_rest_auth.urls")),
        path("core/", include("core.urls")),
        path("chamados/", include("tickets.urls")),
        path("servicos/", include("services.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

api/tickets/urls.py
from rest_framework import routers
from tickets.views import AnexoViewSet, TicketInteracaoViewSet, TicketViewSet

r = routers.DefaultRouter()

r.register("anexos", AnexoViewSet)
r.register("tickets", TicketViewSet)
r.register("ticketsinteracoes", TicketInteracaoViewSet)

urlpatterns = r.urls

api/tickets/models.py
from core.mixins import TimeModelMixin, UserModelMixin
from core.models import User
from django.db import models


def user_directory_path(instance, filename):
    return f"user_{instance.user.username}/{filename}"


class Attachment(models.Model):
    file = models.FileField(upload_to=user_directory_path)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        to="core.User", null=True, blank=True, on_delete=models.CASCADE
    )

    @property
    def name(self):
        return str(self.file).split("/")[-1]

    def __str__(self):
        return f"{self.pk}"


class Ticket(TimeModelMixin, UserModelMixin):
    # STATUS
    STATED = "STATED"
    WORKING = "WORKING"
    MORE_INFORMATION = "MORE_INFORMATION"
    WAITING_CUSTOMER = "WAITING_CUSTOMER"
    NEXT_VERSION = "NEXT_VERSION"
    SOLVED = "SOLVED"
    DEPLOYED = "DEPLOYED"

    # DEPARTMENT
    SUPPORT = "SUPPORT"
    COMMERCIAL = "COMMERCIAL"
    DEVELOPMENT = "DEVELOPMENT"
    FINANCIAL = "FINANCIAL"

    # Priority
    NORMAL = "NORMAL"
    HIGH = "HIGH"

    STATUS = (
        (STATED, "Started"),
        (WORKING, "Working"),
        (MORE_INFORMATION, "More Information"),
        (WAITING_CUSTOMER, "Waiting Customer"),
        (NEXT_VERSION, "In the next version"),
        (SOLVED, "Solved"),
        (DEPLOYED, "Deployed"),
    )

    DEPARTMENTS = (
        (SUPPORT, "Support"),
        (COMMERCIAL, "Commercial"),
        (DEVELOPMENT, "Development"),
        (FINANCIAL, "Financial"),
    )

    PRIORITIES = (
        (NORMAL, "Normal"),
        (HIGH, "High"),
    )
    customer = models.ForeignKey("core.Customer", on_delete=models.CASCADE)

    started_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    finished_at = models.DateTimeField(null=True, blank=True)
    priority = models.CharField(max_length=50, choices=PRIORITIES, default=NORMAL)
    attendant = models.ForeignKey(
        "core.Attendant", on_delete=models.CASCADE, null=True, blank=True
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(max_length=50, choices=STATUS, default=STATED)
    departament = models.CharField(max_length=50, choices=DEPARTMENTS, default=SUPPORT)
    files = models.ManyToManyField(to="tickets.Attachment", blank=True)
    version = models.CharField(max_length=50, null=True, blank=True)
    level = models.IntegerField(default=User.LEVEL1, choices=User.LEVELS)
    service_order = models.ForeignKey(
        "services.ServiceOrder",
        on_delete=models.DO_NOTHING,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Ticket"
        verbose_name_plural = "Tickets"


class TicketInteraction(TimeModelMixin, UserModelMixin):
    ticket = models.ForeignKey("tickets.Ticket", on_delete=models.CASCADE)
    attendant = models.ForeignKey(
        "core.Attendant", on_delete=models.CASCADE, null=True, blank=True
    )
    date = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    description = models.TextField()
    is_internal = models.BooleanField(default=False)
    status = models.CharField(
        max_length=50, choices=Ticket.STATUS, default=Ticket.WORKING
    )
    departament = models.CharField(
        max_length=50, choices=Ticket.DEPARTMENTS, default=Ticket.SUPPORT
    )
    files = models.ManyToManyField(to="tickets.Attachment", blank=True)

    def __str__(self):
        return f"{self.pk}"

    class Meta:
        verbose_name = "Ticket Interaction"
        verbose_name_plural = "Interation of Tickets"
        ordering = ("id",)

api/tickets/views.py
from core.helpers import choice_para_lista
from core.mixins import BaseViewSet
from django.db.models import Q
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from services.serializers import OrdemServicoSerializer
from tickets.models import Attachment, Ticket, TicketInteraction
from tickets.serializers import (
    AnexoSerializer,
    TicketDetalheSerializer,
    TicketInteracaoSerializer,
    TicketSerializer,
)
from tickets.services import TicketDashboardService, TicketRapidoService, TicketService


class AnexoViewSet(BaseViewSet):
    serializer_class = AnexoSerializer
    queryset = Attachment.objects.all().order_by("-pk")
    parser_classes = (
        MultiPartParser,
        FormParser,
    )
    permission_classes = (AllowAny,)


class TicketViewSet(BaseViewSet):
    serializer_class = TicketSerializer
    queryset = Ticket.objects.all().order_by("pk")
    filter_fields = (
        "id",
        "status",
        "prioridade",
        "departamento",
    )

    def get_queryset(self):
        qs = self.queryset

        if self.request.query_params.get("all", None) is not None:
            return qs

        de = self.request.query_params.get("de")
        ate = self.request.query_params.get("ate")

        if de is not None:
            qs = qs.filter(inicio__gte=de)

        if ate is not None:
            qs = qs.filter(inicio__lte=ate)

        excludes = ["sem_atendimento"]
        custom_filters = dict(
            finalizados=Q(status__in=[Ticket.DEPLOYED]),
            sem_atendimento=Q(
                id__in=TicketInteraction.objects.all().values_list("ticket", flat=True)
            ),
        )
        custom_filter = self.request.query_params.get("personalizado", None)

        if custom_filter is not None:
            try:
                filter = custom_filters[custom_filter]
            except:
                qs = qs
            else:
                if custom_filter in excludes:
                    qs = qs.exclude(filter)
                else:
                    qs = qs.filter(filter)

        if self.request.user.is_cliente:
            qs = qs.filter(cliente__usuario_acesso=self.request.user)

            if custom_filter is None:
                qs = qs.exclude(status__in=[Ticket.DEPLOYED])

        if self.request.user.is_atendente:
            qs = qs.filter(
                Q(atendente__usuario_acesso=self.request.user)
                | Q(nivel__lte=self.request.user.level)
            )

            if custom_filter is None:
                qs = qs.exclude(status__in=[Ticket.DEPLOYED])

        if self.request.user.is_superuser:
            qs = qs.order_by("pk")

        return qs

    @action(methods=["post"], detail=False)
    def rapido(self, request, pk=None):
        try:
            data, user = request.date, request.user
            s = TicketRapidoService(data, user)
            data = s.registrar()
            return Response(status=200, data=data)
        except Exception as e:
            return Response(status=400, data=str(e))

    @action(methods=["get"], detail=False)
    def dashboard(self, requests, pk=None):
        ds = TicketDashboardService()
        response = dict(
            status=ds.get_status(),
            totais=ds.get_totais(),
            totais_clientes=ds.get_totais_cliente(),
            totais_atendente=ds.get_totais_atendente(),
        )
        return Response(response)

    @action(methods=["get"], detail=True)
    def detalhes(self, requests, pk=None):
        self.queryset = Ticket.objects.all()

        t = self.get_object()
        return Response(TicketDetalheSerializer(t).data)

    @action(methods=["get"], detail=False)
    def prioridades(self, requests, pk=None):
        return Response(choice_para_lista(Ticket.PRIORITIES))

    @action(methods=["get"], detail=False)
    def status(self, requests, pk=None):
        return Response(choice_para_lista(Ticket.STATUS))

    @action(methods=["get"], detail=False)
    def departamentos(self, requests, pk=None):
        return Response(choice_para_lista(Ticket.DEPARTMENTS))

    @action(methods=["post"], detail=True)
    def upgrade(self, request, pk=None):
        obj = self.get_object()
        try:
            s = TicketService(obj)
            t = s.upgrade(self.request.user)
            return Response(status=200, data=TicketSerializer(t).data)
        except Exception as e:
            return Response(status=400, data=str(e))

    @action(methods=["post"], detail=True)
    def gerar_os(self, request, pk=None):
        try:
            obj = self.get_object()
            s = TicketService(obj)
            os = s.gerar_os(self.request.user)
            return Response(OrdemServicoSerializer(os).data)
        except Exception as e:
            return Response(status=400, data=str(e))


class TicketInteracaoViewSet(BaseViewSet):
    serializer_class = TicketInteracaoSerializer
    queryset = TicketInteraction.objects.all().order_by("pk")

api/tickets/templates/ticket/interacao.html
{% extends 'base_email_tickets.html' %}
{% block content %}
    <div style=" width: 100%; padding: 20px; background: #4B4B4D; color: #FFFFFF">
        <table border="0" cellpadding="0" cellspacing="0" style=" width: 50%; margin: 0 auto; font-size: 22px;">
            <tr>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Ticket</td>
                <td style="font-size: 18px; font-weight: bold; width:40px;">{{ data.id }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Abertura</td>
                <td style="font-size: 18px; font-weight: bold;  width: 270px;">{{ data.inicio }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Cliente</td>
                <td style="font-size: 18px; font-weight: bold; width: auto;">{{ data.cliente.nome }}</td>
            </tr>
        </table>
    </div>
    <table border="0" cellpadding="0" cellspacing="0" style=" width: 800px; margin: 0 auto; padding: 20px;">
        <tr>
            <td style="font-size: 32px;">{{ data.titulo }}</td>
        </tr>
        <tr>
            {% autoescape off %}
                <td style="font-size: 22px;">{{ data.descricao |safe  }}</td>
            {% endautoescape %}
        </tr>

        {% for arquivo in data.arquivos.all %}
            <tr>
                <td style="font-size: 12px;">
                    <a style="text-decoration: none; color: #35459E;" href="{{ arquivo.arquivo }}" target="_blank">{{ arquivo.nome }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <table border="0" cellpadding="0" cellspacing="0" style="width: 800px; margin: 0 auto; padding: 20px;">
        {% if interacao.usuario_logado.is_cliente %}
            <tr>
                <td>{{ interacao.ticket.cliente.nome }}</td>
            </tr>
            <tr>
                {% autoescape off %}
                    <td>{{ interacao.descricao |safe  }}</td>
                {% endautoescape %}
            </tr>
        {% else %}
            <tr style="background: #4B4B4D; color: #FFFFFF;">
                <td style="padding: 20px;">
                    <span style="font-size: 16px; text-transform: uppercase;">{{ interacao.usuario_logado.username }}</span>
                    <span style="font-size: 12px;">em {{ interacao.data }}</span>
                </td>
            </tr>
            <tr>
                {% autoescape off %}
                    <td style="padding: 0 20px; max-width: 800px; overflow: auto;">{{ interacao.descricao |safe  }}</td>
                {% endautoescape %}
            </tr>
            {% for arquivo in interacao.arquivos.all %}
                <tr>
                    <td style="font-size: 12px;">
                        <a style="text-decoration: none; color: #35459E;" href="{{ arquivo.arquivo }}" target="_blank">{{ arquivo.nome }}</a>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>

    <div style=" width: 100%; padding: 20px; background: #4B4B4D; color: #FFFFFF">
        <table border="0" cellpadding="0" cellspacing="0" style="width: 50%; margin: 0 auto; padding: 20px;">
            <tr>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Prioridade</td>
                <td style="font-size: 18px; font-weight: bold;">{{ data.get_prioridade_display }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Status</td>
                <td style="font-size: 18px; font-weight: bold;">{{ data.get_status_display }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Atendente</td>
                <td style="font-size: 18px; font-weight: bold;">{{ data.atendente.nome }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

api/tickets/templates/ticket/novo.html
{% extends 'base_email_tickets.html' %}
{% block content %}
    <div style=" width: 100%; padding: 20px; background: #4B4B4D; color: #FFFFFF">
        <table border="0" cellpadding="0" cellspacing="0" style=" width: 50%; margin: 0 auto; font-size: 22px;">
            <tr>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Ticket</td>
                <td style="font-size: 18px; font-weight: bold; width:40px;">{{ data.id }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Abertura</td>
                <td style="font-size: 18px; font-weight: bold;  width: 270px;">{{ data.inicio }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Cliente</td>
                <td style="font-size: 18px; font-weight: bold; width: auto;">{{ data.cliente.nome }}</td>
            </tr>
        </table>
    </div>
    <table border="0" cellpadding="0" cellspacing="0" style=" width: 800px; margin: 0 auto; padding: 20px;">
        <tr>
            <td style="font-size: 32px;">{{ data.titulo }}</td>
        </tr>
        <tr>
            {% autoescape off %}
                <td style="font-size: 22px;">{{ data.descricao |safe  }}</td>
            {% endautoescape %}
        </tr>

        {% for arquivo in data.arquivos.all %}
            <tr>
                <td style="font-size: 12px;">
                    <a style="text-decoration: none; color: #35459E;" href="{{ arquivo.arquivo }}" target="_blank">{{ arquivo.nome }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>


    <div style=" width: 100%; padding: 20px; background: #4B4B4D; color: #FFFFFF">
        <table border="0" cellpadding="0" cellspacing="0" style="width: 50%; margin: 0 auto; padding: 20px;">
            <tr>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Prioridade</td>
                <td style="font-size: 18px; font-weight: bold;">{{ data.get_prioridade_display }}</td>
                <td style="font-size: 12px; font-weight: 200; width: 80px; text-align: right; padding-right: 4px;">Status</td>
                <td style="font-size: 18px; font-weight: bold;">{{ data.get_status_display }}</td>
            </tr>
        </table>
    </div>
{% endblock %}